import { WORDMARK_W, WORDMARK_H, WORDMARK_D } from './wordmark-data'

/**
 * The "API YES" wordmark in Excalifont, as a single vector path (generated by gen-wordmark.py from the
 * app's own font). Rendered inline with fill=currentColor, so it matches the README lockup glyph-for-
 * glyph yet still recolors with the theme — set the color via CSS (e.g. text-ink). Width follows the
 * given height to preserve the aspect ratio.
 */
export function Wordmark({ height = 20, className }: { height?: number; className?: string }): JSX.Element {
  return (
    <svg
      height={height}
      width={(height * WORDMARK_W) / WORDMARK_H}
      viewBox={`0 0 ${WORDMARK_W} ${WORDMARK_H}`}
      fill="currentColor"
      role="img"
      aria-label="API YES"
      className={className}
    >
      <path d={WORDMARK_D} />
    </svg>
  )
}
